language: "ko-KR"
early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  changed_files_summary: false
  sequence_diagrams: false
  assess_linked_issues: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - "DO NOT REVIEW"
    base_branches:
      - ".*"
  path_filters:
    - "!vendor/**"
    - "!bin/**"
    - "!dist/**"
    - "!*.exe"
    - "!*.test"
    - "!coverage.*"
    - "!go.sum"
  path_instructions:
    - path: "**"
      instructions: |
        - 모든 코드 주석은 반드시 한국어로 작성
        - Go 코딩 컨벤션:
          * Effective Go 및 Go Code Review Comments 가이드라인 준수
          * 에러 처리는 반드시 명시적으로 수행 (에러 무시 금지)
          * 공개 함수/타입은 반드시 GoDoc 주석 작성
        - Go idiom 활용:
          * 인터페이스는 사용하는 쪽에서 정의 (작은 인터페이스 선호)
          * 구조체 임베딩을 통한 컴포지션 활용
          * context.Context를 첫 번째 파라미터로 전달
          * defer를 활용한 리소스 정리
        - 동시성:
          * goroutine 사용 시 반드시 종료 조건 명시
          * channel 또는 sync 패키지를 활용한 동기화
          * race condition 방지를 위한 적절한 동기화 메커니즘 사용
        - 읽기 좋은 코드(가독성)와 유지보수성 중시
        - 각 리뷰 포인트별로 문제점과 대안, 장단점을 논리적으로 제시
  tools:
    gitleaks:
      enabled: true
    golangci-lint:
      enabled: true
    semgrep:
      enabled: true
chat:
  auto_reply: true

knowledge_base:
  web_search:
    enabled: true
  learnings:
    scope: local
  opt_out: false
  code_guidelines:
    enabled: true
